
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.management.openmbean.OpenType;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Emi
 */
public class FutbolManagger extends javax.swing.JFrame {

    DefaultListModel listModelPartidas = new DefaultListModel();
    DefaultListModel listModelTit = new DefaultListModel();
    DefaultListModel listModelSup = new DefaultListModel();
    String equipselec = "";//variable del equipo seleccionado
    String presupuesto = "";//variable del presupuesto de transferencias
    String sueldo = "";//variable del sueldo
    String[] titulares = new String[11];//array contenedor de los jugadores titulares

    /**
     * Creates new form FutbolManagger
     */
    public FutbolManagger() {
        initComponents();
        setLocationRelativeTo(null);
        lstAlineacionTit.setModel(listModelTit);//lista de jugadores titulares
        lstAlineacionSup.setModel(listModelSup);//lista de jugadores suplentes
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmNuevo = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        btnBBVA = new javax.swing.JButton();
        btnBarclays = new javax.swing.JButton();
        btnSerieA = new javax.swing.JButton();
        btnAFA = new javax.swing.JButton();
        btnVolveralm = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        frmBBVA = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        frmAFA = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        btnAllBoys = new javax.swing.JButton();
        btnArgentinos = new javax.swing.JButton();
        btnArsenal = new javax.swing.JButton();
        btnRafaela = new javax.swing.JButton();
        btnBelgrano = new javax.swing.JButton();
        btnBoca = new javax.swing.JButton();
        btnColón = new javax.swing.JButton();
        btnEstud = new javax.swing.JButton();
        btnGodoycr = new javax.swing.JButton();
        btnIndep = new javax.swing.JButton();
        btnLanus = new javax.swing.JButton();
        btnQuilmes = new javax.swing.JButton();
        btnRacing = new javax.swing.JButton();
        btnRiver = new javax.swing.JButton();
        btnSLor = new javax.swing.JButton();
        btnSMdeSJ = new javax.swing.JButton();
        btnTigre = new javax.swing.JButton();
        btnUnion = new javax.swing.JButton();
        btnVelez = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblJugadoresclave = new javax.swing.JLabel();
        lblPresupuesto = new javax.swing.JLabel();
        lblObjetivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAlineacionTit = new javax.swing.JList();
        lblSueldo = new javax.swing.JLabel();
        lblDificultad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlineacionSup = new javax.swing.JList();
        btnNuls = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        lblEquiposelec = new javax.swing.JLabel();
        btnSigEq = new javax.swing.JButton();
        btnAtrEq = new javax.swing.JButton();
        frmJugar = new javax.swing.JFrame();
        btnNuevapart = new javax.swing.JButton();
        btnCargarpart = new javax.swing.JButton();
        frmRegistrarse = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnSiguienteFinal = new javax.swing.JButton();
        cmbxContexturafis = new javax.swing.JComboBox();
        dlgErrorCargar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        btnAtrasPCargadas = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnAcercade = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        frmNuevo.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione una liga:");

        btnBBVA.setText("Liga BBVA");
        btnBBVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBVAActionPerformed(evt);
            }
        });

        btnBarclays.setText("Barclays PL");

        btnSerieA.setText("Serie A");

        btnAFA.setText("AFA");
        btnAFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAFAActionPerformed(evt);
            }
        });

        btnVolveralm.setText("Volver al menú principal");
        btnVolveralm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolveralmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmNuevoLayout = new javax.swing.GroupLayout(frmNuevo.getContentPane());
        frmNuevo.getContentPane().setLayout(frmNuevoLayout);
        frmNuevoLayout.setHorizontalGroup(
            frmNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBBVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBarclays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSerieA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(frmNuevoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAFA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmNuevoLayout.createSequentialGroup()
                        .addGap(0, 235, Short.MAX_VALUE)
                        .addComponent(btnVolveralm))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        frmNuevoLayout.setVerticalGroup(
            frmNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmNuevoLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnBBVA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBarclays, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSerieA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAFA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolveralm)
                .addContainerGap())
        );

        jLabel2.setText("Seleccione un equipo:");

        jButton1.setText("Athletic de Bilbao");

        jButton2.setText("Atlético de Madrid");

        javax.swing.GroupLayout frmBBVALayout = new javax.swing.GroupLayout(frmBBVA.getContentPane());
        frmBBVA.getContentPane().setLayout(frmBBVALayout);
        frmBBVALayout.setHorizontalGroup(
            frmBBVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBBVALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmBBVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        frmBBVALayout.setVerticalGroup(
            frmBBVALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmBBVALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        frmAFA.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Seleccione un equipo:");

        btnAllBoys.setText("All Boys");
        btnAllBoys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllBoysActionPerformed(evt);
            }
        });

        btnArgentinos.setText("Argentinos");
        btnArgentinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArgentinosActionPerformed(evt);
            }
        });

        btnArsenal.setText("Arsenal");
        btnArsenal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArsenalActionPerformed(evt);
            }
        });

        btnRafaela.setText("Atl Rafaela");
        btnRafaela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRafaelaActionPerformed(evt);
            }
        });

        btnBelgrano.setText("Belgrano");
        btnBelgrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelgranoActionPerformed(evt);
            }
        });

        btnBoca.setText("Boca");
        btnBoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBocaActionPerformed(evt);
            }
        });

        btnColón.setText("Colón");
        btnColón.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColónActionPerformed(evt);
            }
        });

        btnEstud.setText("Estudiantes");
        btnEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudActionPerformed(evt);
            }
        });

        btnGodoycr.setText("Godoy Cruz");
        btnGodoycr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGodoycrActionPerformed(evt);
            }
        });

        btnIndep.setText("Independiente");
        btnIndep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndepActionPerformed(evt);
            }
        });

        btnLanus.setText("Lanús");
        btnLanus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanusActionPerformed(evt);
            }
        });

        btnQuilmes.setText("Quilmes");
        btnQuilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuilmesActionPerformed(evt);
            }
        });

        btnRacing.setText("Racing");
        btnRacing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacingActionPerformed(evt);
            }
        });

        btnRiver.setText("River");
        btnRiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiverActionPerformed(evt);
            }
        });

        btnSLor.setText("San Lorenzo");
        btnSLor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSLorActionPerformed(evt);
            }
        });

        btnSMdeSJ.setText("SM de SJ");
        btnSMdeSJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSMdeSJActionPerformed(evt);
            }
        });

        btnTigre.setText("Tigre");
        btnTigre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTigreActionPerformed(evt);
            }
        });

        btnUnion.setText("Unión");
        btnUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnionActionPerformed(evt);
            }
        });

        btnVelez.setText("Velez");
        btnVelez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVelezActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Presupuesto:");

        jLabel5.setText("Jugadores Clave:");

        jLabel8.setText("Objetivo:");

        jLabel9.setText("Alineación:");

        jLabel10.setText("Sueldo:");

        jLabel11.setText("Dificultad:");

        jScrollPane1.setViewportView(lstAlineacionTit);

        jScrollPane2.setViewportView(lstAlineacionSup);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblJugadoresclave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblObjetivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblJugadoresclave, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDificultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnNuls.setText("Newell's");
        btnNuls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNulsActionPerformed(evt);
            }
        });

        jLabel12.setText("Equipo seleccionado:");

        btnSigEq.setText("Siguiente");
        btnSigEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigEqActionPerformed(evt);
            }
        });

        btnAtrEq.setText("Atrás");

        javax.swing.GroupLayout frmAFALayout = new javax.swing.GroupLayout(frmAFA.getContentPane());
        frmAFA.getContentPane().setLayout(frmAFALayout);
        frmAFALayout.setHorizontalGroup(
            frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmAFALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(frmAFALayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(lblEquiposelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmAFALayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtrEq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSigEq))
                    .addGroup(frmAFALayout.createSequentialGroup()
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBelgrano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRafaela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnArsenal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnArgentinos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAllBoys, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBoca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnColón, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEstud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGodoycr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIndep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLanus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuilmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRacing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRiver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSLor, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(btnSMdeSJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTigre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVelez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUnion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frmAFALayout.setVerticalGroup(
            frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmAFALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmAFALayout.createSequentialGroup()
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAllBoys)
                            .addComponent(btnLanus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArgentinos)
                            .addComponent(btnNuls))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArsenal)
                            .addComponent(btnQuilmes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRafaela)
                            .addComponent(btnRacing))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBelgrano)
                            .addComponent(btnRiver))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBoca)
                            .addComponent(btnSLor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnColón)
                            .addComponent(btnSMdeSJ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEstud)
                            .addComponent(btnTigre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGodoycr)
                            .addComponent(btnUnion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIndep)
                            .addComponent(btnVelez))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEquiposelec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmAFALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSigEq)
                    .addComponent(btnAtrEq))
                .addContainerGap())
        );

        frmJugar.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNuevapart.setText("Nueva partida");
        btnNuevapart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevapartActionPerformed(evt);
            }
        });

        btnCargarpart.setText("Cargar partida ultima partida guardada");
        btnCargarpart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarpartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmJugarLayout = new javax.swing.GroupLayout(frmJugar.getContentPane());
        frmJugar.getContentPane().setLayout(frmJugarLayout);
        frmJugarLayout.setHorizontalGroup(
            frmJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmJugarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevapart, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(btnCargarpart, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        frmJugarLayout.setVerticalGroup(
            frmJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmJugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevapart)
                .addGap(18, 18, 18)
                .addComponent(btnCargarpart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frmRegistrarse.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setText("Nombre y apellido:");

        jLabel14.setText("Edad:");

        jLabel15.setText("Contextura física:");

        txtNombre.setText("ass");

        txtEdad.setText("23");

        btnSiguienteFinal.setText("Siguiente");
        btnSiguienteFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteFinalActionPerformed(evt);
            }
        });

        cmbxContexturafis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Delgado", "Normal", "Robusto" }));

        javax.swing.GroupLayout frmRegistrarseLayout = new javax.swing.GroupLayout(frmRegistrarse.getContentPane());
        frmRegistrarse.getContentPane().setLayout(frmRegistrarseLayout);
        frmRegistrarseLayout.setHorizontalGroup(
            frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addGroup(frmRegistrarseLayout.createSequentialGroup()
                        .addGroup(frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(71, 71, Short.MAX_VALUE)
                        .addGroup(frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEdad)
                            .addComponent(txtNombre)
                            .addComponent(cmbxContexturafis, 0, 220, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmRegistrarseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSiguienteFinal)))
                .addContainerGap())
        );
        frmRegistrarseLayout.setVerticalGroup(
            frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRegistrarseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frmRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbxContexturafis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSiguienteFinal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("No hay partidas guardadas anteriormente. Inicie una nueva partida.");

        btnAtrasPCargadas.setText("Atras");

        javax.swing.GroupLayout dlgErrorCargarLayout = new javax.swing.GroupLayout(dlgErrorCargar.getContentPane());
        dlgErrorCargar.getContentPane().setLayout(dlgErrorCargarLayout);
        dlgErrorCargarLayout.setHorizontalGroup(
            dlgErrorCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgErrorCargarLayout.createSequentialGroup()
                .addGroup(dlgErrorCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgErrorCargarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(dlgErrorCargarLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnAtrasPCargadas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlgErrorCargarLayout.setVerticalGroup(
            dlgErrorCargarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgErrorCargarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtrasPCargadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(415, 340));
        getContentPane().setLayout(null);

        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar);
        btnJugar.setBounds(10, 210, 380, 23);

        btnAcercade.setText("Acerca de");
        getContentPane().add(btnAcercade);
        btnAcercade.setBounds(10, 240, 380, 23);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(10, 270, 380, 23);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondoprincipal.jpg"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        frmJugar.setVisible(true);
        frmJugar.setSize(400, 350);
        frmJugar.setLocationRelativeTo(null);
        this.hide();

    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVolveralmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolveralmActionPerformed
        // TODO add your handling code here:
        new FutbolManagger().setVisible(true);
        frmNuevo.hide();
    }//GEN-LAST:event_btnVolveralmActionPerformed

    private void btnBBVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBBVAActionPerformed

    private void btnAFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAFAActionPerformed
        // TODO add your handling code here:
        frmAFA.setVisible(true);
        frmAFA.setSize(740, 600);
        frmAFA.setLocationRelativeTo(null);
        frmNuevo.hide();
    }//GEN-LAST:event_btnAFAActionPerformed

    private void btnNuevapartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevapartActionPerformed
        // TODO add your handling code here:
        frmNuevo.setVisible(true);
        frmNuevo.setSize(400, 350);
        frmNuevo.setLocationRelativeTo(null);
        frmJugar.hide();
        CrearArchivo e = new CrearArchivo();
        e.nuevoarchivoindividual("Partidos jugados", "0");//al comenzar una nueva partida los partidos jugados son 0
    }//GEN-LAST:event_btnNuevapartActionPerformed

    private void btnCargarpartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarpartActionPerformed
//        // TODO add your handling code here:
//        LeerArchivo s = new LeerArchivo();
//        int guardado = Integer.parseInt(s.leerstring("Guardado.txt"));
//        if (guardado == 1){
//            new MenuJuego().setVisible(true);
//            int cargado = 1;
//            CrearArchivo a = new CrearArchivo();
//            a.nuevoarchivoindividual("Cargado", "1");
//            this.hide();
//        }
//        if (guardado == 0){
//            dlgErrorCargar.setVisible(true);
//            dlgErrorCargar.setLocationRelativeTo(null);
//        }
    }//GEN-LAST:event_btnCargarpartActionPerformed

    private void btnAllBoysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllBoysActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();//limpiamos la lista de los jugadores suplentes
        listModelSup.addElement("            Suuplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();//limpiamos la lista de los jugadores titulares
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("All Boys");//determinamos el equipo seleccionado
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("All Boys Presupuesto.txt");//el presupuesto es determinado para cada equipo guardado en un txt para cada uno de ellos
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("All Boys Sueldo.txt");//el sueldo es guardado igual que el presupuesto
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("All Boys Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);//se dan como datos los jugadores clave de cada equipo
        String dificultad = a.leerstring("All Boys Dificultad.txt");
        lblDificultad.setText(dificultad);//dependiendo de que equipo es variara la dificultad
        String objetivo = a.leerstring("All Boys Objetivo.txt");
        lblObjetivo.setText(objetivo);//el objetivo es distinto para cada equipo dependiendo de sus caracteristicas
        titulares = a.leerarray("All Boys Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);//almacenamos los jugadores titulares en una lista
        }
        String[] suplentes = a.leerarray("All Boys Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);//almacenamos los jugadores suplentes en una lista
        }
        
    }//GEN-LAST:event_btnAllBoysActionPerformed

    private void btnArgentinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArgentinosActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Argentinos");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Argentinos Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Argentinos Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Argentinos Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Argentinos Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Argentinos Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("C:Argentinos Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Argentinos Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnArgentinosActionPerformed

    private void btnArsenalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArsenalActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Arsenal");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Arsenal Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Arsenal Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Arsenal Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Arsenal Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Arsenal Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Arsenal Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Arsenal Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnArsenalActionPerformed

    private void btnRafaelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRafaelaActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Atlético Rafaela");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Atl Rafaela Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Atl Rafaela Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Atl Rafaela Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Atl Rafaela Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Atl Rafaela Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Atl Rafaela Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Atl Rafaela Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnRafaelaActionPerformed

    private void btnBelgranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelgranoActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Belgrano");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Belgrano Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Belgrano Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Belgrano Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Belgrano Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Belgrano Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Belgrano Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Belgrano Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnBelgranoActionPerformed

    private void btnBocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBocaActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Boca");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        sueldo = a.leerstring("Boca Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Boca Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Boca Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Boca Objetivo.txt");
        lblObjetivo.setText(objetivo);
        presupuesto = a.leerstring("Boca Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        titulares = a.leerarray("Boca Titulares.txt");
        for (int i = 0; i < 11; i++) {
            String titular = titulares[i];
            listModelTit.addElement(titular);
        }
        String[] suplentes = a.leerarray("Boca Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnBocaActionPerformed

    private void btnColónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColónActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Colon");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Colon Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Colon Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Colon Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Colon Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Colon Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Colon Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Colon Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnColónActionPerformed

    private void btnEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Estudiantes");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Estudiantes Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Estudiantes Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Estudiantes Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Estudiantes Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Estudiantes Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Estudiantes Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Estudiantes Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnEstudActionPerformed

    private void btnGodoycrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGodoycrActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Godoy Cruz");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Godoy Cruz Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Godoy Cruz Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Godoy Cruz Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Godoy Cruz Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Godoy Cruz Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Godoy Cruz Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Godoy Cruz Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnGodoycrActionPerformed

    private void btnIndepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndepActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Independiente");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Independiente Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Independiente Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Independiente Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Independiente Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Independiente Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Independiente Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Independiente Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnIndepActionPerformed

    private void btnLanusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanusActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Lanús");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Lanus Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Lanus Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Lanus Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Lanus Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Lanus Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Lanus Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Lanus Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnLanusActionPerformed

    private void btnNulsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNulsActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Newell's");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Newells Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Newells Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Newells Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Newells Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Newells Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Newells Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Newells Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnNulsActionPerformed

    private void btnQuilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuilmesActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Quilmes");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Quilmes Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Quilmes Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Quilmes Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Quilmes Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Quilmes Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Quilmes Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Quilmes Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnQuilmesActionPerformed

    private void btnRacingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacingActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Racing");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Racing Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Racing Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Racing Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Racing Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Racing Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Racing Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Racing Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnRacingActionPerformed

    private void btnRiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiverActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("River");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("River Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("River Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("River Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("River Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("River Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("River Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("River Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnRiverActionPerformed

    private void btnSLorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSLorActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("San Lorenzo");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("San Lorenzo Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("San Lorenzo Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("San Lorenzo Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("San Lorenzo Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("San Lorenzo Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("San Lorenzo Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("San Lorenzo Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnSLorActionPerformed

    private void btnSMdeSJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSMdeSJActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("San Martín de San Juan");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("SM de SJ Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("SM de SJ Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("SM de SJ Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("SM de SJ Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("SM de SJ Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("SM de SJ Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("SM de SJ Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnSMdeSJActionPerformed

    private void btnTigreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTigreActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Tigre");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Tigre Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Tigre Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Tigre Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Tigre Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Tigre Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Tigre Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Tigre Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnTigreActionPerformed

    private void btnUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Unión");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Union Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Union Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Union Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Union Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Union Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Union Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Union Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnUnionActionPerformed

    private void btnVelezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVelezActionPerformed
        // TODO add your handling code here:
        listModelSup.clear();
        listModelSup.addElement("            Suplentes");
        listModelSup.addElement("****************************************");
        listModelTit.clear();
        listModelTit.addElement("            Titulares");
        listModelTit.addElement("****************************************");
        lblEquiposelec.setText("Velez");
        equipselec = lblEquiposelec.getText();
        LeerArchivo a = new LeerArchivo();
        presupuesto = a.leerstring("Velez Presupuesto.txt");
        lblPresupuesto.setText("$" + presupuesto);
        sueldo = a.leerstring("Velez Sueldo.txt");
        lblSueldo.setText("$"+sueldo);
        String jugadoresclave = a.leerstring("Velez Jugadores clave.txt");
        lblJugadoresclave.setText(jugadoresclave);
        String dificultad = a.leerstring("Velez Dificultad.txt");
        lblDificultad.setText(dificultad);
        String objetivo = a.leerstring("Velez Objetivo.txt");
        lblObjetivo.setText(objetivo);
        titulares = a.leerarray("Velez Titulares.txt");
        for (int i = 0; i < 11; i++) {
            listModelTit.addElement(titulares[i]);
        }
        String[] suplentes = a.leerarray("Velez Suplentes.txt");
        for (int e = 0; e < 8; e++){
            String suplente = suplentes[e];
            listModelSup.addElement(suplente);
        }
    }//GEN-LAST:event_btnVelezActionPerformed

    private void btnSigEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigEqActionPerformed
        // TODO add your handling code here:
        frmRegistrarse.setVisible(true);
        frmRegistrarse.setSize(450, 215);
        frmRegistrarse.setLocationRelativeTo(null);
        frmAFA.hide();
    }//GEN-LAST:event_btnSigEqActionPerformed

    private void btnSiguienteFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteFinalActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        String contfis = (String) cmbxContexturafis.getSelectedItem();
        String equipo = equipselec;
        int transferencias = Integer.parseInt(presupuesto);
        int sueldofirmado = Integer.parseInt(sueldo);
        int edad = Integer.parseInt(txtEdad.getText());
        CrearArchivo e = new CrearArchivo();
        e.nuevoarchivocompleto("Datos del DT", nombre, equipo, ""+transferencias, ""+edad);
        e.nuevoarchivoindividual("Nombre del DT",nombre);
        e.nuevoarchivoindividual("Edad del DT", ""+edad);
        e.nuevoarchivoindividual("Equipo del DT", equipo);
        e.nuevoarchivoindividual("Transferencias del DT", ""+transferencias);
        Dt dt = new Dt(nombre, contfis, equipo, edad, sueldofirmado, transferencias);
        txtNombre.setText(null);
        txtEdad.setText(null);
        cmbxContexturafis.setSelectedItem(1);
        frmRegistrarse.hide();
        new MenuJuego().setVisible(true);
    }//GEN-LAST:event_btnSiguienteFinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */


        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FutbolManagger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FutbolManagger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FutbolManagger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FutbolManagger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new FutbolManagger().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAFA;
    private javax.swing.JButton btnAcercade;
    private javax.swing.JButton btnAllBoys;
    private javax.swing.JButton btnArgentinos;
    private javax.swing.JButton btnArsenal;
    private javax.swing.JButton btnAtrEq;
    private javax.swing.JButton btnAtrasPCargadas;
    private javax.swing.JButton btnBBVA;
    private javax.swing.JButton btnBarclays;
    private javax.swing.JButton btnBelgrano;
    private javax.swing.JButton btnBoca;
    private javax.swing.JButton btnCargarpart;
    private javax.swing.JButton btnColón;
    private javax.swing.JButton btnEstud;
    private javax.swing.JButton btnGodoycr;
    private javax.swing.JButton btnIndep;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnLanus;
    private javax.swing.JButton btnNuevapart;
    private javax.swing.JButton btnNuls;
    private javax.swing.JButton btnQuilmes;
    private javax.swing.JButton btnRacing;
    private javax.swing.JButton btnRafaela;
    private javax.swing.JButton btnRiver;
    private javax.swing.JButton btnSLor;
    private javax.swing.JButton btnSMdeSJ;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSerieA;
    private javax.swing.JButton btnSigEq;
    private javax.swing.JButton btnSiguienteFinal;
    private javax.swing.JButton btnTigre;
    private javax.swing.JButton btnUnion;
    private javax.swing.JButton btnVelez;
    private javax.swing.JButton btnVolveralm;
    private javax.swing.JComboBox cmbxContexturafis;
    private javax.swing.JDialog dlgErrorCargar;
    private javax.swing.JFrame frmAFA;
    private javax.swing.JFrame frmBBVA;
    private javax.swing.JFrame frmJugar;
    private javax.swing.JFrame frmNuevo;
    private javax.swing.JFrame frmRegistrarse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDificultad;
    private javax.swing.JLabel lblEquiposelec;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblJugadoresclave;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblPresupuesto;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JList lstAlineacionSup;
    private javax.swing.JList lstAlineacionTit;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
